### ISSUE TITLE
Feature Requests:  Schema Selection For Launch Device Side

### ISSUE THREAD

**Issue by RudiShumpert** [adobe/alloy#623] opened 2020-10-28 15:37 UTC
### Expected Behaviour

Modify the AEP Web SDK Extension to set a default XDM Schema in the extension configuration so that it does not have to be set for every data element that uses the Extension.

### Actual Behaviour
NA
### Reproduce Scenario (including but not limited to)
NA
#### Steps to Reproduce
NA
#### Platform and Version
NA
#### Sample Code that illustrates the problem
NA
#### Logs taken while reproducing problem
NA
![Screen Shot 2020-10-28 at 11 34 52 AM](https://user-images.githubusercontent.com/37945125/97459224-eb6f2400-1911-11eb-95b7-ababc96e89b7.png)

**Comment by jfkhoury** [comment] 2020-11-03 16:55
Duplicate of #631 . Will be closing this one.

**Closed by jfkhoury** 2020-11-03 16:55 UTC
